### ISSUE TITLE
something went wrong...

### ISSUE THREAD

**Issue by woolf0007** [Aohzan/hass-polar#1]
Hi,
you would be the greatest king if it worked again after all this time!
But after the add integration- client ID and secret, it is shows the polar website with "oops something went wrong" text...
Sorry, for me it is not working...
are you sure the format of redirect url is:
https://myexternalaccess/api/polar_auth

**Comment by Aohzan** [comment]
Hi,
yes, for me :
![image](https://user-images.githubusercontent.com/2736322/208624001-79895731-461c-45e2-8109-f0fa22fb3394.png)

**Comment by woolf0007** [comment]
ok, i have no idea, why isnt working for me:
![auth polar](https://user-images.githubusercontent.com/72889318/208625321-692ce899-f4eb-453b-99d1-456261492492.JPG)

**Comment by woolf0007** [comment]
are you use the latest HA ?
![HA](https://user-images.githubusercontent.com/72889318/208625992-f18f6a5a-a614-42ad-b878-e0f529897430.JPG)

**Comment by Aohzan** [comment]
yes, can you paste me the URL opened by HA ? you can get it on the button when returning on HA interface:
![image](https://user-images.githubusercontent.com/2736322/208626272-9faf487b-ece8-499e-87d9-7d9ac680e736.png)

**Comment by woolf0007** [comment]
https://flow.polar.com/oauth2/authorization?client_id=XXXX&response_type=code&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiZGIxMDdlNDIyZjNlNGMxYmQ2NmRlMmQ4ZjZlYzNiZWYiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3dvbGZwcm9qZWN0YnQuZHluZG5zLm9yZy8vYXBpL3BvbGFyX2F1dGgifQ.0MbJch_XYQoVdZ9jkXnIE4qkyyP6CuRHyrEzgkNyPB4&redirect_uri=https%3A%2F%2FXXXX%2F%2Fapi%2Fpolar_auth
the ID and domain is correct (I replaced with XXXX)

**Comment by Aohzan** [comment]
the client id match your URL in your access link account ? (in case you have multiple client created)

**Comment by woolf0007** [comment]
how can i text you in private?

**Comment by woolf0007** [comment]
you mean, i shoult find my client id in my profile on https://flow.polar.com/ ?

**Comment by woolf0007** [comment]
i have only 1 client in the acceslink list
![client list](https://user-images.githubusercontent.com/72889318/208630744-bcd78317-58f7-4ff9-95b2-6d726f8db871.JPG)

**Comment by Aohzan** [comment]
can you try to reset client secrets
![image](https://user-images.githubusercontent.com/2736322/208631091-68770a33-f556-4d97-be7f-65e87d23690d.png)

**Comment by woolf0007** [comment]
i reseted this already, not working.
in the URL and and cient ID is same i checked
![match](https://user-images.githubusercontent.com/72889318/208631996-c2f221b3-3519-4bfa-afae-a6939f8dda6e.JPG)

**Comment by Aohzan** [comment]
can you enable debug log and check if you have something in it ?

**Comment by woolf0007** [comment]
have you seen the right corner up of my picture before that
i want to give my id to try

**Comment by woolf0007** [comment]
sorry im not that expert, i see the logbook, nothing interest..

**Comment by Aohzan** [comment]
is your external url reachable from your computer ?

**Comment by woolf0007** [comment]
it is working perfect, i reach all of my system from outside.

**Comment by woolf0007** [comment]
I've only been struggling with polar for a long time, there might be something wrong

**Comment by Aohzan** [comment]
can you try to delete the client in Access Link and recreate a new one from scratch

**Comment by woolf0007** [comment]
my solution was, to link polar with strava and HA read data from strava...but this involves data loss
therefore i dont want to delete my client. do you think this accesslink client needs to strava or unnecessary?

**Comment by woolf0007** [comment]
if i make a new client?

**Comment by Aohzan** [comment]
yes you can

**Comment by woolf0007** [comment]
![image](https://user-images.githubusercontent.com/72889318/208639852-19c0ca7b-c707-4948-a82c-d3028471ce00.png)

**Comment by woolf0007** [comment]
![image](https://user-images.githubusercontent.com/72889318/208640042-827aa109-6f44-486b-9cff-81ab0f6e61f6.png)

**Comment by woolf0007** [comment]
![image](https://user-images.githubusercontent.com/72889318/208640605-66ce71f9-eab4-4e59-8071-9608aff0f53b.png)

**Comment by woolf0007** [comment]
new ID new secret etc...
same, sorry

**Comment by woolf0007** [comment]
https://flow.polar.com/oauth2/authorization?client_id=xx&response_type=code&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiM2I1YTFhYWY2MGE0MTZjYWZlZjZhOTNjNDFmN2EwODkiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3dvbGZwcm9qZWN0YnQuZHluZG5zLm9yZy8vYXBpL3BvbGFyX2F1dGgifQ.Td65Pv9BJgQkQhhCMfv43juCheE9l5-8mgzsB8_wDgQ&redirect_uri=https%3A%2F%2Fxx%2F%2Fapi%2Fpolar_auth
the domain and id is the same

**Comment by Aohzan** [comment]
I don't understand what's going wrong :thinking: if you enable debug log:
```---
logger:
  logs:
    custom_components.polar: debug```
and check logs in Settings => System => Logs

**Comment by Aohzan** [comment]
if we could get a test from someone else

**Comment by woolf0007** [comment]
ok, I'll google how to do this and write, thx your effort

**Comment by doctorjames** [comment]
This has happened to me too. I can't debug now, but will try and collect logs soon.

**Comment by woolf0007** [comment]
> This has happened to me too. I can't debug now, but will try and collect logs soon.

i dont now how debug, pls write if you are successfull

**Comment by woolf0007** [comment]
thx for the next release, but it still won't let me in after the ID and secret... :(

**Comment by Aohzan** [comment]
can you contact me on aohzan@gmail.com, maybe I can test some creds you created

**Comment by woolf0007** [comment]
ok

**Comment by woolf0007** [comment]
Hey Mattieu, i caught an error log:
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/polar/polaraccesslink/oauth2.py:116
Integration: Polar (documentation, issues)
First occurred: December 22, 2022 at 11:54:13 PM (2 occurrences)
Last logged: 11:25:57 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 171, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 281, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/polar/config_flow.py", line 105, in async_step_creation
    token_response = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/polar/polaraccesslink/accesslink.py", line 57, in get_access_token
    return self.oauth.get_access_token(authorization_code)
  File "/config/custom_components/polar/polaraccesslink/oauth2.py", line 74, in get_access_token
    return self.post(
  File "/config/custom_components/polar/polaraccesslink/oauth2.py", line 141, in post
    return self.__request("post", endpoint=endpoint, **kwargs)
  File "/config/custom_components/polar/polaraccesslink/oauth2.py", line 133, in __request
    return self.__parse_response(response)
  File "/config/custom_components/polar/polaraccesslink/oauth2.py", line 116, in __parse_response
    raise HTTPError(message, response=response)
requests.exceptions.HTTPError: 400 Bad Request: {"error":"invalid_request"}
Pls help if you understand it...thx

**Comment by Aohzan** [comment]
it seems that Polar return something wrong to HA :thinking: 
what did you get on Polar, no more "oops something went wrong" error ?

**Comment by woolf0007** [comment]
On afternoon i will send you a video about the process... im not at home
now...

Matthieu ***@***.***> ezt írta (időpont: 2022. dec. 23., Pén
12:09):

**Comment by daveflanagan52** [comment]
I had a trailing slash in my home assistant's configured external URL, removing that resolved this error for me and looks to be the same issue experienced by @woolf0007 judging by two `%2F` in your URL
(Side note: `Use Home Assistant Cloud` toggle does not work when active, the redirect URL ends up being `None`)

**Comment by Aohzan** [comment]
thank you @daveflanagan52 , I will handle this in a fix

**Comment by Aohzan** [comment]
@woolf0007 can you test the 0.2.0 release ?

**Comment by woolf0007** [comment]
Wow,  I was one step ahead! Thx Matthieu.
Now i need to investigate why the sensors unavailable...
![Screenshot_20221230_080434_Home Assistant](https://user-images.githubusercontent.com/72889318/210043915-15b7acee-1a18-4ccc-986d-773edcd29a05.jpg)

**Comment by Aohzan** [comment]
It's like it don't have access to those data
![image](https://user-images.githubusercontent.com/2736322/210049766-9020a94c-b152-4f4b-b4d4-1e3dda4480c1.png)

**Comment by woolf0007** [comment]
Hi, Mattieu,
Ok, thx, I swiched off and on and the data came! All working fine!
what do you think i can turn on these sensors in yaml to get more data? as in the old version like this: (I am most interested in the training data)
polar:
    client_id: xxx
    client_secret: xxx
    unit_system: metric # Defaults to global unit_system if not specified
    monitored_resources:
        daily_activity:
            - "calories"
            - "duration"
            - "active-calories"
            - "active-steps"
        training_data:
            - "calories"
            - "club-id"
            - "club-name"
            - "detailed-sport-info"
            - "device"
            - "distance"
            - "duration"
            - "has-route"
            - "heart-rate/average"
            - "heart-rate/maximum"
            - "start-time"
            - "sport"
            - "training-load"
        physical_info:
            - "aerobic-threshold"
            - "anaerobic-threshold"
            - "height"
            - "maximum-heart-rate"
            - "resting-heart-rate"
            - "vo2-max"
            - "weight

**Comment by Aohzan** [comment]
you'll find those information in the sensor attributes

**Comment by woolf0007** [comment]
ok, i see it! thx
