### ISSUE TITLE
invalid unique_id

### ISSUE THREAD

**Issue by nblount** [Aohzan/hass-polar#10]
Seeing this error in the logs:

Config entry '**** ******' from integration polar has an invalid unique_id '15593274', please create a bug report at https://github.com/Aohzan/hass-polar/issues

**Comment by Aohzan** [comment]
I need more details, diagnostic of the integration and debug logs for example

**Comment by nblount** [comment]
Other than that log entry I am not seeing anything else.  The integration appears to be working fine.

**Comment by Aohzan** [comment]
Can you test to delete your configuration entry and add it again ?

**Comment by nblount** [comment]
Removed and added same error appears.

**Comment by Aohzan** [comment]
Enable debug logs, reload the integration and paste logs please

**Comment by nblount** [comment]
home-assistant.log:2024-11-03 12:32:47.831 ERROR (MainThread) [homeassistant.config_entries] Config entry '**** ******' from integration polar has an invalid unique_id '15593274', please create a bug report at https://github.com/Aohzan/hass-polar/issues
home-assistant.log:2024-11-03 12:32:53.141 DEBUG (SyncWorker_29) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/15593274
home-assistant.log:2024-11-03 12:32:53.390 DEBUG (SyncWorker_18) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/exercises
home-assistant.log:2024-11-03 12:32:53.505 DEBUG (SyncWorker_20) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/sleep/
home-assistant.log:2024-11-03 12:32:53.919 DEBUG (SyncWorker_12) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/nightly-recharge/
home-assistant.log:2024-11-03 12:32:54.098 DEBUG (SyncWorker_29) [custom_components.polar.polaraccesslink.oauth2] POST request to URL: https://www.polaraccesslink.com/v3/users/15593274/activity-transactions
home-assistant.log:2024-11-03 12:32:54.218 DEBUG (SyncWorker_29) [custom_components.polar.polaraccesslink.accesslink] No daily activity available, will try for the next sync
home-assistant.log:2024-11-03 12:32:54.244 DEBUG (MainThread) [custom_components.polar] Finished fetching polar data in 1.103 seconds (success: True)
home-assistant.log:2024-11-03 13:02:56.143 DEBUG (SyncWorker_15) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/15593274
home-assistant.log:2024-11-03 13:02:56.295 DEBUG (SyncWorker_26) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/exercises
home-assistant.log:2024-11-03 13:02:56.378 DEBUG (SyncWorker_60) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/sleep/
home-assistant.log:2024-11-03 13:02:56.837 DEBUG (SyncWorker_21) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/nightly-recharge/
home-assistant.log:2024-11-03 13:02:57.035 DEBUG (SyncWorker_18) [custom_components.polar.polaraccesslink.oauth2] POST request to URL: https://www.polaraccesslink.com/v3/users/15593274/activity-transactions
home-assistant.log:2024-11-03 13:02:57.119 DEBUG (SyncWorker_18) [custom_components.polar.polaraccesslink.accesslink] No daily activity available, will try for the next sync
home-assistant.log:2024-11-03 13:02:57.119 DEBUG (MainThread) [custom_components.polar] Finished fetching polar data in 0.977 seconds (success: True)
home-assistant.log:2024-11-03 13:27:27.234 DEBUG (SyncWorker_25) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/15593274
home-assistant.log:2024-11-03 13:27:27.417 DEBUG (SyncWorker_16) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/exercises
home-assistant.log:2024-11-03 13:27:27.504 DEBUG (SyncWorker_0) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/sleep/
home-assistant.log:2024-11-03 13:27:27.927 DEBUG (SyncWorker_51) [custom_components.polar.polaraccesslink.oauth2] GET request to URL: https://www.polaraccesslink.com/v3/users/nightly-recharge/
home-assistant.log:2024-11-03 13:27:28.117 DEBUG (SyncWorker_24) [custom_components.polar.polaraccesslink.oauth2] POST request to URL: https://www.polaraccesslink.com/v3/users/15593274/activity-transactions
home-assistant.log:2024-11-03 13:27:28.200 DEBUG (SyncWorker_24) [custom_components.polar.polaraccesslink.accesslink] No daily activity available, will try for the next sync
home-assistant.log:2024-11-03 13:27:28.200 DEBUG (MainThread) [custom_components.polar] Finished fetching polar data in 0.966 seconds (success: True)

**Comment by Aohzan** [comment]
should be fix in https://github.com/Aohzan/hass-polar/releases/tag/1.3.1 (need 2 restart)
