### ISSUE TITLE
FYI, it's spelled "Exercise"

### ISSUE THREAD

**Issue by cinghialino** [Aohzan/hass-polar#3]
One of the sensor reports an "last_exercice" which is incorrect spelling.
Please fix it.

**Comment by Aohzan** [comment]
Maybe you can start by a Hello...

**Comment by Aohzan** [comment]
https://github.com/Aohzan/hass-polar/releases/tag/1.0.0

**Comment by cinghialino** [comment]
Hi Matthieu, 

Some devs like to go straight to the point, some don't. You can never get it right. I indeed appreciate your work, and thank you for fixing it so fast. 

Best
