### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by Aohzan** [Aohzan/hass-polar#5]
The webpage return me:
¡VAYA! ALGO FUE MAL. INTÉNTALO DE NUEVO MÁS TARDE.

I completed client id, password ... and when I was redirected to  Polar Web for confirm in HA ....¡VAYA! ALGO FUE MAL. INTÉNTALO DE NUEVO MÁS TARDE.

_Originally posted by @jesusmendez87 in https://github.com/Aohzan/hass-polar/issues/4#issuecomment-1450969144_

**Comment by Aohzan** [comment]
hello @jesusmendez87 
should be fixed in the last release, can you update, restart and check ?

(can you translate in english next time please)

**Comment by jesusmendez87** [comment]
I maked all but i have the same problem... After completing the data in HA. I am redirected to https://flow.polar.com/oauth2/authorization?client_id=0d7746f4-0c39-4a6a-xxxxxxxxxxxxxxxxxxxxf&response_type=code&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc&redirect_uri=https%3A%2F%2Fxxxxxxxxxxxxxxxxxxxxxx.org%2Fapi%2Fpolar_auth

and webpage return me: OH! SOMETHING WAS WRONG. TRY AGAIN LATER.

**Comment by Aohzan** [comment]
can you try with an other url without `/api/polar_auth` in polar access link ? (see https://github.com/Aohzan/hass-polar/discussions/2)

**Comment by jesusmendez87** [comment]
I installed and tried to remove /api/polar. I am redirected to the main page of HA but without changes. It does not generate any entities and I can continue trying to install the plugin without any change

**Comment by jesusmendez87** [comment]
finally I can install

![image](https://user-images.githubusercontent.com/72827621/224168316-6f912fff-049e-4e23-9f81-7d75c2fc857e.png)

**Comment by Aohzan** [comment]
ok thank you I will add it to the readme
