### ISSUE TITLE
Sensors unavailable

### ISSUE THREAD

**Issue by XalaTheShepard** [Aohzan/hass-polar#8]
Good afternoon everyone, 

I installed this custom component and created the client ID and client secret. 
Although they were accepted by the integration, the only sensor that is not "unavailable" is the sensor "weight". 
All other sensors remain unavailable. 
Is there some kind of step that I am missing? 

Thanks in advance. 

Kind regards.

**Comment by Aohzan** [comment]
Hello
do you have an error in logs ?

**Comment by XalaTheShepard** [comment]
Home Assistant Core
No issues found for search term 'polar'

**Comment by XalaTheShepard** [comment]
Some additional information: 

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4987
Installed Version | 1.32.1
Stage | running
Available Repositories | 1337
Downloaded Repositories | 50

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 97.7 GB
disk_used | 20.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.6.0), AppDaemon (0.13.3), Spotify Connect (0.12.4), Terminal & SSH (9.7.1), Home Assistant Google Drive Backup (0.111.1), Node-RED (14.4.2), AdGuard Home (4.8.12), Samba share (10.0.2), Studio Code Server (5.9.0), UniFi Network Application (2.7.0), Mosquitto broker (6.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 16
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 14, 2023 at 7:53 AM
-- | --
current_recorder_run | July 23, 2023 at 4:32 PM
estimated_db_size | 481.56 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Aohzan** [comment]
can you enable debug logs and paste them
![image](https://github.com/Aohzan/hass-polar/assets/2736322/21da6a49-a724-4ae8-9adb-e2388ed18e26)
![image](https://github.com/Aohzan/hass-polar/assets/2736322/34e97c55-620a-4406-91e9-ecf41f157a1a)

**Comment by XalaTheShepard** [comment]
Dear Aohzan, I have found the error. Apparently the Polar watch did not sync correctly, but now it does and the issue is solved.
